config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  #resources :estagios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "inicials#index"
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  #get '/estagio_export' => 'estagios#export'
  get '/estagio_exportinscritos' => 'estagios#exportinscritos'

  resources :estagios do
    member do
      get 'export'
    end
  end

  #root :to => 'inicials#index'

  resources :inicials
  get 'inicial', to: 'inicials#index'
  post 'inicial', to: 'inicials#index'
end

app/models/estagio.rb
class Estagio < ApplicationRecord
  validate :valida_nome
  validate :valida_dtNasc
  validate :valida_naturalidade
  validate :valida_sexo
  validate :valida_rg
  validate :valida_dtEmissao
  validates_presence_of :orgaoEmissao, message: ' - Este campo deve ser preenchido.'
  validate :valida_cpf
  validates :cpf, uniqueness: {message: ' - já cadastrado'}
  validate :valida_tel1
  validate :valida_tel2
  validate :valida_email
  validate :valida_cep
  validate :valida_bairro
  validate :valida_logradouro
  validate :valida_num
  validate :valida_cidade
  validate :valida_estado
  validate :valida_area
  validate :valida_instituicao
  validate :valida_curso
  validate :valida_sem
  validate :valida_durCurso
  validate :valida_necEsp
  #validate :valida_descricaoEsp
  
  #Formataçõesi
  def numero_inscricao
    return nil unless self.persisted?

    id_com_zeros = "%04d" % self.id
    "#{id_com_zeros}#{self.created_at.year}"
  end
  
  def tel1format
    return nil unless self.persisted?
    tel1format = "(" << self.tel1[0..1] << ") " << self.tel1[2..6] << "-" << self.tel1[7..10]
    tel1format
  end
  
  def tel2format
    return nil unless self.persisted?
    tel2format = "(" << self.tel2[0..1] << ") " << self.tel2[2..6] << "-" << self.tel2[7..10]
    tel2format
  end
  
  def cpfformat
    return nil unless self.persisted?
    cpfformat = self.cpf[0..2] << "." << self.cpf[3..5] << "." << self.cpf[6..8] << "-" << self.cpf[9..10]
    cpfformat
  end
  
  def dtNascformat
    dataNascformat = self.dtNasc[0..1] << "/" << self.dtNasc[2..3] << "/" << self.dtNasc[4..7]
    dataNascformat
  end
  
  def dtEmissaoformat
    dataEmissaoformat = self.dtEmissao[0..1] << "/" << self.dtEmissao[2..3] << "/" << self.dtEmissao[4..7]
    dataEmissaoformat
  end
  
  def desNecEspformat
    if self.desNecEsp.blank?
      desNecEspformat = "Não possui"
    else
      self.desNecEsp
    end
  end
  
  def nomeformat
    nomeformat = self.nome.titleize
    nomeformat
  end
  
  def naturalidadeformat
    naturalidadeformat = self.naturalidade.titleize
    naturalidadeformat
  end
  
  def logradouroformat
    logradouroformat = self.logradouro.titleize
    logradouroformat
  end
  
  def orgaoEmissaoformat
    orgaoEmissaoformat = self.orgaoEmissao.upcase
    orgaoEmissaoformat
  end
  
  def bairroformat
    bairroformat = self.bairro.titleize
    bairroformat
  end
  
  #Formataçõesf
  
  #Validação CPFi
  def check_cpf
    return false if self.cpf.nil?

    winvalidos = %w{12345678909 11111111111 22222222222 33333333333 44444444444 55555555555 66666666666 77777777777 88888888888 99999999999 00000000000}
    wvalor = cpf.scan /[0-9]/
    if wvalor.length == 11
      unless winvalidos.member?(wvalor.join)
	wvalor = wvalor.collect{|x| x.to_i}
	wsoma = 10*wvalor[0]+9*wvalor[1]+8*wvalor[2]+7*wvalor[3]+6*wvalor[4]+5*wvalor[5]+4*wvalor[6]+3*wvalor[7]+2*wvalor[8]
	wsoma = wsoma - (11 * (wsoma/11))
	wresult1 = (wsoma == 0 or wsoma == 1) ? 0 : 11 - wsoma
	if wresult1 == wvalor[9]
	  wsoma = wvalor[0]*11+wvalor[1]*10+wvalor[2]*9+wvalor[3]*8+wvalor[4]*7+wvalor[5]*6+wvalor[6]*5+wvalor[7]*4+wvalor[8]*3+wvalor[9]*2
	  wsoma = wsoma - (11 * (wsoma/11))
	  wresult2 = (wsoma == 0 or wsoma == 1) ? 0 : 11 - wsoma
	  return true if wresult2 == wvalor[10] # CPF validado
	end
      end
    end
    return false # CPF invalidado
  end
  #Validação CPFf
  
  #Buscai
  def self.search(search)
    where("cpf LIKE ?", "%#{search}%")
  end
  
  def self.searchpag(search)
    where("pag LIKE ?", "%#{search}%") 
  end
  
  def self.searcharea(search)
    where("area LIKE ?", "%#{search}%") 
  end
  
  def self.searchsexo(search)
    where("sexo LIKE ?", "%#{search}%") 
  end
  
  def self.searchnome(search)
    where("nome LIKE ?", "%#{search}%") 
  end
  
  def self.searchins(search)
    where("id LIKE ?", "%#{search}%") 
  end
  #Buscaf
  
  private  
  def valida_nome
    if nome.blank?
      validates_presence_of :nome, message: ' deve ser preenchido.'
    else
      validates_length_of :nome, within: 5..100, too_long: ' deve possuir no máximo 100 caracteres.', too_short: 'deve possuir no mínimo 5 caracteres.'
      errors.add(:nome, " deve ter somente letras.") unless nome =~ /^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/
    end
  end
  
  def valida_dtNasc
    if dtNasc.blank?
      validates_presence_of :dtNasc, message: ' deve ser preenchido.'
    else
      errors.add(:dtNasc, " deve estar no formato ddMMaaaa") unless dtNasc =~ /[0-9]+$/ and dtNasc.size == 8
    end
  end
  
  def valida_naturalidade
    if naturalidade.blank?
      validates_presence_of :naturalidade, message: ' deve ser preenchido.'
    else
      validates_length_of :naturalidade, within: 3..50, too_long: ' deve possuir no máximo 50 caracteres.', too_short: ' deve possuir no mínimo 3 caracteres.'
      errors.add(:naturalidade, " deve ter somente letras.") unless naturalidade =~ /^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/
    end
  end
  
  def valida_sexo
    if sexo.blank?
      validates_presence_of :sexo, message: ' deve ser preenchido.'
    else
      errors.add("sexo", " - Este campo aceita somente 'Feminino' ou 'Masculino'.") unless sexo == "Feminino" or sexo == "Masculino"
    end
  end
  
  def valida_rg
    if rg.blank?
      validates_presence_of :rg, message: ' - Este campo deve ser preenchido.'
    else
      #errors.add("rg", " - Este campo deve ter somente números.") unless rg  =~ /^[\d]+$/ 
      errors.add("rg", " deve ter no máximo 20 dígitos.") unless rg.size <= 20
    end
  end
  
  def valida_dtEmissao
    if dtEmissao.blank?
      validates_presence_of :dtEmissao, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("dtEmissao", " - Este campo deve estar no formato: ddMMaaaa.") unless dtEmissao.size == 8
      #errors.add("dtEmissao", " - não pode ser menor que a Data de Nascimento") unless dtEmissao < dtNasc
      #validar se a data de emissão do rg é maior que o ano de nascimento
    end
  end
  
  def valida_cpf
    if cpf.blank?
      validates_presence_of :cpf, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("cpf", " - inválido") unless check_cpf == true
    end
  end
  
  def valida_tel1
    if tel1.blank?
      validates_presence_of :tel1, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("tel1", " - Este campo deve estar no formato: 96900001111") unless tel1  =~ /[0-9]+$/ and tel1.size == 11
    end
  end
  
  def valida_tel2
    if tel2.blank?
      validates_presence_of :tel2, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("tel2", " - Este campo deve estar no formato: 96900001111") unless tel2  =~ /[0-9]+$/  and tel2.size == 11
      #/[0-9]{2}[0-9]{4,6}[0-9]{3,4}$/
    end
  end
         
  def valida_email
    if email.blank?
      validates_presence_of :email, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("email", " - Este campo deve estar no formato: e-mail@email.com") unless email =~ /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/
    end
  end
  
  def valida_cep
    if cep.blank?
      validates_presence_of :cep, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("cep", " - Este campo deve estar no formato: 00111333") unless cep =~ /[0-9]{5}[0-9]{3}/ and cep.size <= 9
    end
  end
  
  def valida_bairro
    if bairro.blank?
      validates_presence_of :bairro, message: ' - Este campo deve ser preenchido.'
    else
      validates_length_of :bairro, maximum: 30, too_long: ' - Este campo deve ter no máximo 30 caracteres.'
    end
  end
  
  def valida_logradouro
    if logradouro.blank?
      validates_presence_of :logradouro, message: ' - Este campo deve ser preenchido.'
    else
      validates_length_of :logradouro, maximum: 60, too_long: ' - Este campo deve ter no máximo 60 caracteres.'
    end
  end
  
  def valida_num
    if num.blank?
      validates_presence_of :num, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("num", " - Este campo deve ser preenchido com números.") unless num =~/^[\d]+$/
      validates_length_of :num, maximum: 10, too_long: ' - Este campo deve ter no máximo 10 dígitos.'
    end
  end
  
  def valida_cidade
    if cidade.blank?
      validates_presence_of :cidade, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("cidade", " - Cidade inválida.") unless cidade == "Amapá" or cidade == "Calçoene" or cidade == "Cutias" or cidade == "Ferreira Gomes" or cidade == "Itaubal" or cidade == "Laranjal do Jari" or cidade == "Macapá" or cidade == "Mazagão" or cidade == "Oiapoque" or cidade == "Pedra Branca do Amapari" or cidade == "Porto Grande" or cidade == "Pracuúba" or cidade == "Santana" or cidade == "Serra do Navio" or cidade == "Tartarugalzinho" or cidade == "Vitória do Jari"
    end
  end
  
  def valida_estado
    if estado.blank?
      validates_presence_of :estado, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("estado", " - Estado inválido.") unless estado == "Amapá"
    end
  end
  
  def valida_area
    if area.blank?
      validates_presence_of :area, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("area", " - Área inválida.") unless area == "Administração" or area == "Contabilidade" or area == "Direito" or area == "Informática"
    end
  end
  
  def valida_instituicao
    if instituicao.blank?
      validates_presence_of :instituicao, message: ' - Este campo deve ser preenchido.'
    else
      errors.add("instituicao", " - Instituição inválida.") unless instituicao == "Ceap" or instituicao == "Fabran" or instituicao == "Fama" or instituicao == "Famap" or instituicao == "Ifap" or instituicao == "Seama" or instituicao == "Unifap"
    end
  end
  
  def valida_curso
    if curso.blank?
      validates_presence_of :curso, message: ' - Este campo deve ser preenchido.'
    else

app/controllers/estagios_controller.rb
class EstagiosController < ApplicationController
  before_action :set_estagio, only: [:show, :edit, :update, :destroy, :export]
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :export, :exportinscritos]
  #before_action :authorize_comprovante, only: [:export]
  
  require './lib/generate_pdf'
  require './lib/inscritos_pdf'
  # GET /estagios
  # GET /estagios.json
 #'/estagios?order=ASC'
  def index
    @estagios = policy_scope(Estagio).all
    @a = 0
    #busca
    if params[:search]
      @estagios = Estagio.search(params[:search]).order("nome ASC") #ordenando em ordem afabética
    else if params[:searchpag]
      @estagios = Estagio.searchpag(params[:searchpag]).order("nome ASC") #ordenando em ordem afabética
    else if params[:searcharea]
      @estagios = Estagio.searcharea(params[:searcharea]).order("nome ASC") #ordenando em ordem afabética
    else if params[:searchsexo]
      @estagios = Estagio.searchsexo(params[:searchsexo]).order("nome ASC") #ordenando em ordem afabética
    else if params[:searchnome]
      @estagios = Estagio.searchnome(params[:searchnome]).order("nome ASC") #ordenando em ordem afabética
    else if params[:searchins]
      @estagios = Estagio.searchins(params[:searchins]).order("nome ASC") #ordenando em ordem afabética
    else
      @estagios = policy_scope(Estagio).all.order("id ASC")
    end
    end
    end
    end
    end
    end
  end

  # GET /estagios/1
  # GET /estagios/1.json
  def show
  end

  # GET /estagios/new
  def new
    if user_signed_in?
      @estagios = policy_scope(Estagio).all
      @estagio = Estagio.new
    else
    @estagio = Estagio.new
    end
  end

  # GET /estagios/1/edit
  def edit
  end

  # POST /estagios
  # POST /estagios.json
  def create
    @estagio = Estagio.new(estagio_params)
    
    respond_to do |format|
      if @estagio.save
        format.html { redirect_to @estagio, notice: 'Inscrição realizada com sucesso.' }
        format.json { render :show, status: :created, location: @estagio }
      else
        format.html { render :new }
        format.json { render json: @estagio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estagios/1
  # PATCH/PUT /estagios/1.json
  def update
    respond_to do |format|
      if @estagio.update(estagio_params_update)
        format.html {  redirect_back(fallback_location: estagios_path, notice: 'Dados atualizados com sucesso.')  }
        format.json { render :show, status: :ok, location: @estagios }
      else
        format.html { render :edit }
        format.json { render json: @estagio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estagios/1
  # DELETE /estagios/1.json
  def destroy
    @estagio.destroy
    respond_to do |format|
      format.html { redirect_to estagios_url, notice: 'Inscrição removida com sucesso.' }
      format.json { head :no_content }
    end
  end
  
  def export
    GeneratePdf::estagio(@estagio.id, @estagio.nomeformat, @estagio.dtNascformat, @estagio.naturalidadeformat, @estagio.sexo, @estagio.rg, @estagio.dtEmissaoformat, @estagio.orgaoEmissaoformat, @estagio.cpfformat, @estagio.tel1format, @estagio.tel2format, @estagio.email, @estagio.cep, @estagio.logradouroformat, @estagio.num, @estagio.bairroformat, @estagio.cidade, @estagio.estado, @estagio.area, @estagio.instituicao, @estagio.curso, @estagio.sem, @estagio.durCurso, @estagio.necEsp, @estagio.desNecEspformat, @estagio.numero_inscricao)
    redirect_to "/fichainscricao_#{@estagio.id}.pdf"
    #@estagios = policy_scope(Estagio).all.order("nome ASC")
    #GeneratePdf::estagio(Estagio.all.order("nome ASC"))
    #GeneratePdf::estagio(Estagio.all.each {|e| [e.nomeformat, e.area, e.pag]})
    #redirect_to '/estagio.pdf'
    #redirect_to "/fichainscricao_#{id}.pdf"
  end
  
  def exportinscritos
    GeneratePdfInscritos::estagio(Estagio.all.order("nome ASC"))
    redirect_to "/lista_inscritos.pdf"
  end
  #def inscritospdf
  #  Inscritos::estagio(@estagios.id, @estagios.nome, @estagios.sexo, @estagios.rg, @estagios.cpf, @estagios.area, @estagios.curso, @estagios.necEsp, @estagios.desNecEsp, @estagios.numero_inscricao)
  #  #GeneratePdf::agreement(@agreement.client_name, @agreement.description, @agreement.price)
  #  redirect_to "/listainscritos.pdf"
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estagio
      @estagio = Estagio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estagio_params
      params.require(:estagio).permit(:nome, :dtNasc, :naturalidade, :sexo, :rg, :dtEmissao, :orgaoEmissao, :cpf, :tel1, :tel2, :email, :cep, :logradouro, :num, :bairro, :cidade, :estado, :area, :instituicao, :curso, :sem,:durCurso, :necEsp, :desNecEsp, :numInsc, :pag).merge(user_id: current_user.id)
    end
    
    def estagio_params_update
      params.require(:estagio).permit(:nome, :dtNasc, :naturalidade, :sexo, :rg, :dtEmissao, :orgaoEmissao, :cpf, :tel1, :tel2, :email, :cep, :logradouro, :num, :bairro, :cidade, :estado, :area, :instituicao, :curso, :sem,:durCurso, :necEsp, :desNecEsp, :numInsc, :pag)
    end
    
    #def authorize_comprovante
    #  authorize @estagio
    #end

end

app/helpers/estagios_helper.rb
module EstagiosHelper
  def telformat(tel)
    telformat = "("
    telformat << tel[0..1]
    telformat << ") "
    telformat << tel[2..6]
    telformat << "-"
    telformat << tel[7..10]
    telformat
  end
  
  def cpfformat(cpf)
    cpfformat = cpf[0..2] << "." << cpf[3..5] << "." << cpf[6..8] << "-" << cpf[9..10]
    cpfformat
  end
  
  def dataformat(data)
    dataformat = data[0..1] << "/" << data[2..3] << "/" << data[4..7]
  end
end

app/views/estagios/edit.html.erb
<%- model_class = Estagio -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= link_to t('.back', :default => t("helpers.links.back")),
              estagios_path, :class => 'links'  %>
<%= link_to 'Comprovante de Inscrição', export_estagio_path(@estagio),
	           :class => 'links2'%>

<% if current_user.admin? or current_user.admin2? or current_user.id == @estagio.user_id%>
  <%= render :partial => 'form' %>
<% else %>
  Você não pode alterar essa inscrição.
<% end %>

app/views/estagios/index.html.erb
<% if current_user.try(:admin?) or current_user.try(:admin2?) %>
  <h1>Lista Inscritos no PS Estágio SJAP</h1>

<% @estagios.each do |estagio| %>
<% @a = @a + 1%>
<% end %>
  
  <p>
  <%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= select_tag :searcha, options_for_select(@estagios.collect{ |e| [e.id] }) %>
     <%= select_tag :searchb, options_for_select(@estagios.collect{ |e| [e.id] }) %>
    <%= submit_tag "Pesquisar" %>
  <% end %>
    
  <%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= search_field_tag :search, params[:search], placeholder: "CPF" %>
  <% end %>
  
  <%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= search_field_tag :searchnome, params[:searchnome], placeholder: "Nome" %>
  <% end %>
    
  <%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= search_field_tag :searchins, params[:searchins], placeholder: "Inscrição" %>
  <% end %>

  <%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= select_tag :searchpag, options_for_select('Confirmada' => 'confirmada'), prompt: 'Doação', :onchange => "this.form.submit();" %>
  <% end %>

 <%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= select_tag :searcharea, options_for_select('Administração' => "administração", 'Contailidade' => "contabilidade", 'Direito' => "Direito", 'Informática' => "informática"), prompt: 'Área', :onchange => "this.form.submit();" %>
  <% end %>

<%= form_tag(estagios_path, :method => "get", id: "search-form") do %>
    <%= select_tag :searchsexo, options_for_select('Feminino' => "feminino", 'Masculino' => "masculino"), prompt: 'Sexo', :onchange => "this.form.submit();" %>
  <% end %>

  <% if @estagios.present? %>
    <%= link_to 'Voltar', method: :index %>
    <% else %>
      <p>Não foram encontrados resultados.</p>
      <%= link_to 'Voltar', method: :index %>
  <% end %>
</p>

  <% else %>
  <h1>Processo Seletivo para Estagiários da Justiça Federal da 1ª Região
    Seção Judiária do Amapá</h1>
  <h2>Suas Inscrições</h2>
<% end %>

<p><%= render "estagios/navbar"%></p>

<% if @estagios.blank? and not current_user.try(:admin?) and not current_user.try(:admin2?) %>
<p>No momento você ainda não possui nenhuma inscrição.</p>
<p>
  Para efetuar sua inscrição clique em <%= link_to 'Realizar inscrição', new_estagio_path, :class => "links" %>
</p>

<% else if not current_user.try(:admin?) and not current_user.try(:admin2?) %>
  <table class="lista-inscritos">
    <thead>
      <tr>
      	<th>Inscrição</th>
      	<th>Nome</th>
      	<th>Sexo</th>
      	<th>RG</th>
      	<th>CPF</th>
      	<th>Área</th>
      	<th>Curso</th>
      	<th>Portador de Necessidades Especiais</th>
      	<th>Doação</th>
      	<th colspan="4">Opções</th>
      </tr>
    </thead>

    <tbody>
      <% @estagios.each do |estagio| %>
		<tr>
		  <td><%= estagio.numero_inscricao %></td>
		  <td><%= estagio.nomeformat %></td>
		  <td><%= estagio.sexo %></td>
		  <td><%= estagio.rg %></td>
		  <td><%= estagio.cpfformat %></td>
		  <td><%= estagio.area %></td>
		  <td><%= estagio.curso %></td>
		  <td><%= estagio.necEsp %></td>
		  <td><%= estagio.pag %></td>
			<td>
			  <%= link_to image_tag("info",
				  onmouseover: "this.src='#{asset_path('info_hover')}'",
				  onmouseout:  "this.src='#{asset_path('info')}'"),
				  estagio, title: "Ver detalhes"  %>
			  <%#= link_to 'Ver detalhes', estagio %>
			</td>
			<td>
			  <%= link_to image_tag("edit",
			      onmouseover: "this.src='#{asset_path('edit_hover')}'",
			      onmouseout:  "this.src='#{asset_path('edit')}'"),
			      edit_estagio_path(estagio), title: "Editar dados" %>
			  <%#= link_to 'Editar dados', edit_estagio_path(estagio) %>
			</td>
			<td>
			  <%= link_to image_tag("file"), export_estagio_path(estagio),
			      title: "Emitir Comprovante de Inscrição", class: "icones", target: "_blank" %>
			  <%#= link_to 'Comprovante de Inscrição', export_estagio_path(estagio),
			       target: "_blank" %>
			</td>
		</tr>
      <% end %>
    </tbody>
  </table> 
<% end %>
<% end %>

<% if not @estagios.blank? and current_user.try(:admin?) %>
<p>Resultado: <%= @a %></p>
  <table class="lista-inscritos">
    <thead>
      <tr>
        <th>Inscrição</th>
        <th>Nome</th>
        <th>Sexo</th>
        <th>CPF</th>
        <th>Área</th>
        <th>Curso</th>
        <th>SA/DC</th>
        <th>Portador de Necessidades Especiais</th>
        <th>Doação</th>
        <th colspan="4">Opções</th>
      </tr>
    </thead>

  <tbody>
    <% @estagios.each do |estagio| %>
    <% @a = @a + 1%>
      <tr>
		<td><%= estagio.numero_inscricao %></td>
		    <td><%= estagio.nomeformat %></td>
		    <td><%= estagio.sexo %></td>
		    <td><%= estagio.cpfformat %></td>
		    <td><%= estagio.area %></td>
        <td><%= estagio.curso %></td>
        <td><%= estagio.sem %>/<%= estagio.durCurso %> </td>
		    <td><%= estagio.necEsp %></td>
		    <td>
		  <% if current_user.admin? and estagio.pag == "Pendente" or estagio.pag.blank?  %>
        Pendente
		  <% else %>
			  <%= estagio.pag %>
		  <% end %>
		</td>
		<td>
		  <%= link_to image_tag("info",
		      onmouseover: "this.src='#{asset_path('info_hover')}'",
		      onmouseout:  "this.src='#{asset_path('info')}'"),
		      estagio, title: "Ver detalhes"  %>
		  <%#= link_to 'Ver detalhes', estagio %>
		</td>
		<td>
	      <%= link_to image_tag("edit",
	          onmouseover: "this.src='#{asset_path('edit_hover')}'",
	          onmouseout:  "this.src='#{asset_path('edit')}'"),
	          edit_estagio_path(estagio), title: "Editar dados" %>
	      <%#= link_to 'Editar dados', edit_estagio_path(estagio) %>
		</td>
		<td>
	      <%= link_to image_tag("file"), export_estagio_path(estagio),
	          title: "Emitir Comprovante de Inscrição", class: "icones", target: "_blank" %>
	      <%#= link_to 'Comprovante de Inscrição', export_estagio_path(estagio),
	           target: "_blank" %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<% if current_user.try(:admin?) %>
  <%= link_to 'Nova Inscrição', new_estagio_path %>
  <%= link_to 'Lista Inscritos Confirmados', estagio_exportinscritos_path, target: "_blank"%>
<% end %>


<% if not @estagios.blank? and current_user.try(:admin2?) %>
<p>Resultado: <%= @a %></p>
  <table class="lista-inscritos">
    <thead>
      <tr>
	<th>Inscrição</th>
	<th>Nome</th>
  <th>CPF</th>
	<th>Área</th>
	<th>Curso</th>
	<th>Doação</th>
      </tr>
    </thead>

    <tbody>
      <% @estagios.each do |estagio| %>
      <% @a = @a + 1%>
	<tr>
	  <td><%= estagio.numero_inscricao %></td>
	  <td><%= estagio.nomeformat %></td>
    <td><%= estagio.cpfformat %></td>
	  <td><%= estagio.area %></td>
	  <td><%= estagio.curso %></td>
	  <td>
	    <% if current_user.admin2? and estagio.pag == "Pendente" or estagio.pag.blank? %>
	      Pendente
	    <% else %>
	      <%= estagio.pag %>
	    <% end %>
	  </td>
	</tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/estagios/inicial.html.erb
<h1>
  Página Inicial
</h1>

<p>
  <%= link_to 'Cadastre-se', new_user_registration_path %> no site.
</p>
<p>
  <%= link_to 'Acesse', user_session_path %>.
</p>
<p>
  <%= link_to 'Inscreva-se', new_estagio_path %>.
</p>