config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  #resources :estagios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "inicials#index"
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  #get '/estagio_export' => 'estagios#export'
  get '/estagio_exportinscritos' => 'estagios#exportinscritos'

  resources :estagios do
    member do
      get 'export'
    end
  end

  #root :to => 'inicials#index'

  resources :inicials
  get 'inicial', to: 'inicials#index'
  post 'inicial', to: 'inicials#index'
end

app/views/layouts/_sidebar.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>Publicações</h3>
    <ul class="nav nav-list">
      <li class="nav-header">Acesso a links</li>
      <li><%= link_to "Upload da documentação de alguma coisa..", "/path1"  %></li>
      <li><%= link_to "Lista de Inscritos", "/path2"  %></li>
      <li><%= link_to "Locais de Prova", "/path3"  %></li>
    </ul>
    <ul class="nav nav-list">
      <li class="nav-header">Editais, Comunicados e informações</li>
      <li><%= link_to "Edital de Abertura", "/path1"  %></li>
      <li><%= link_to "Lista de Inscritos", "/path2"  %></li>
      <li><%= link_to "Locais de Prova", "/path3"  %></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

<%#= link_to 'Página Principal', estagios_path %>

<%#= link_to "Logout", destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Seleção de Estagiários - 2018</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application',
          media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
          'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div id="header-wrap">
        <%= image_tag("logo.png",
          html: { title: "Justiça Federal - Seção Judiária do Amapá" } ) %>
      </div><!-- div id="header-wrap" -->
      <nav>
        <div id="menu">
          <ul>
            <li><%= link_to "Página Inicial", inicials_path %></li>
            <li><%= link_to "Portal da Justiça Federal",
                            "http://portal.trf1.jus.br/sjap" %></li>
            <li><%= link_to "Edital e mais informações", "http://portal.trf1.jus.br/sjap/concursos/estagios/ps-secao-judiciaria-do-amapa-2018.htm" %></li>
          </ul>
        </div>
      </nav>
    </header>

    <div id="content">

      <% if notice.present? %>
        <u><p id="notice"><%= notice %></p></u>
      <% end %>
      <% if alert.present? %>
        <p id="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div><!-- div id="content" -->

    <!--div id="rodape">
        <footer>
            <p>Edifício-sede: Rodovia Norte-Sul, s/n, Bairro: Infraero II, Macapá-AP</p>
            <p>CEP: 68908-911 Telefone: (96) 3214-1500</p>
            <p>CNPJ: 05.426.574/0001-40</p>
        </footer>
    </div> <!/rodape -->
  </body>
</html>